name: Secrets Management

on:
  # schedule:
  #   - cron: '*/15 8-20 * 09 1-5'
  workflow_dispatch:

jobs:
  secrets-management:
    name: secret-management
    runs-on: traffic-runners
    if: github.event_name == 'schedule' 
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://traffic-g00.ams.creativecdn.net/
          method: jwt
          role: traffic-vault-configuration-ci
          secrets: |
            traffic-team-dev/misc asana_access_token | ASANA_ACCESS_TOKEN
            traffic-vault/gitlab_project_tokens configuration | GITLAB_TOKEN
      - name: Setup environment variables
        run: |
          echo "CI_SERVER_HOST=github.com" >> $GITHUB_ENV
          echo "CI_PROJECT_PATH=${{ github.repository }}" >> $GITHUB_ENV
          echo "CI_SERVER_URL=https://github.com" >> $GITHUB_ENV
          echo "CI_DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
          echo "GITLAB_USER_EMAIL=${{ github.event.repository.owner.email || 'noreply@github.com' }}" >> $GITHUB_ENV
          echo "GITLAB_USER_NAME=${{ github.event.repository.owner.name || 'GitHub Actions' }}" >> $GITHUB_ENV
          echo "CI_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Run secret management script
        working-directory: scripts/secret-management
        env:
          ASANA_ACCESS_TOKEN: ${{ env.ASANA_ACCESS_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_SERVER_HOST: ${{ env.CI_SERVER_HOST }}
          CI_PROJECT_PATH: ${{ env.CI_PROJECT_PATH }}
          CI_SERVER_URL: ${{ env.CI_SERVER_URL }}
          CI_DEFAULT_BRANCH: ${{ env.CI_DEFAULT_BRANCH }}
          GITLAB_USER_EMAIL: ${{ env.GITLAB_USER_EMAIL }}
          GITLAB_USER_NAME: ${{ env.GITLAB_USER_NAME }}
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
        run: |
          bash secret-management.sh
