name: Upload files to GCS

on:
  push:
    branches:
      - main
    paths:
      - "secret_engines_secrets.json"
      - ".github/workflows/upload-files-gcs.yml"
  workflow_dispatch:

jobs:
  upload-files-to-gcs:
    permissions:
      contents: "read"
      id-token: "write"
    uses: RTBHouse-Traffic/common-workflows/.github/workflows/upload-files-gcs.yml@main
    with:
      project_id: "traffic-team-admin"
      bucket_name: "traffic-seda-metadata-prod"
      destination: "secrets"
      path: "."
      glob: "secret_engines_secrets.json"
      parent: false
    secrets: inherit
